---
abstract: 'Config::Any loader for Log4perl config files.'
author:
  - 'Loïc TROCHET <losyme@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Any-Log4perl
no_index:
  directory:
    - t
    - inc
requires:
  Config::Any: 0
  parent: 0
resources:
  repository: https://github.com/losyme/Config-Any-Log4perl
version: 0.02
